---

- name: Bunch of IOS tasks
  hosts: all
  gather_facts: false
  tasks:
    - name: run show version on remote devices
      cisco.ios.ios_command:
        command: show version

    - name: run show version and check to see if output contains IOS
      cisco.ios.ios_command:
        command: show version
        wait_for: result[0] contains IOS

    - name: run multiple commands on remote nodes
      cisco.ios.ios_command:
        command:
        - show version
        - show interfaces
